-- Indexes for performance
CREATE INDEX idx_settlement_race_estimate_details_estimate_id ON gaming.settlement_race_estimate_details(settlement_race_estimate_id);
CREATE INDEX idx_settlement_race_estimate_details_bet_id ON gaming.settlement_race_estimate_details(bet_id);
CREATE INDEX idx_settlement_race_estimate_details_deleted_at ON gaming.settlement_race_estimate_details(deleted_at);